// Generated by Sterling SDK Generator
// Orchestrator Control Plane API v0.1.0

const std = @import("std");
const Allocator = std.mem.Allocator;

pub const ClientOptions = struct {
    base_url: ?[]const u8 = null,
    api_key: ?[]const u8 = null,
    max_retries: u32 = 2,
    timeout_ms: u64 = 30_000,
};

pub const Response = struct {
    status: std.http.Status,
    body: []const u8,
    allocator: Allocator,

    pub fn deinit(self: *Response) void {
        self.allocator.free(self.body);
    }

    pub fn json(self: *const Response) !std.json.Parsed(std.json.Value) {
        return std.json.parseFromSlice(std.json.Value, self.allocator, self.body, .{ .allocate = .alloc_always });
    }
};

pub const RequestOptions = struct {
    timeout_ms: ?u64 = null,
};

pub const ApiError = error{
    BadRequest, Unauthorized, Forbidden, NotFound, Conflict,
    UnprocessableEntity, RateLimited, InternalServerError,
    ConnectionError, Unexpected,
};

fn statusToError(status: std.http.Status) ApiError!void {
    return switch (@intFromEnum(status)) {
        200...299 => {},
        400 => ApiError.BadRequest,
        401 => ApiError.Unauthorized,
        403 => ApiError.Forbidden,
        404 => ApiError.NotFound,
        409 => ApiError.Conflict,
        422 => ApiError.UnprocessableEntity,
        429 => ApiError.RateLimited,
        500...599 => ApiError.InternalServerError,
        else => ApiError.Unexpected,
    };
}

fn isRetryable(status: std.http.Status) bool {
    const code = @intFromEnum(status);
    return code >= 500 or code == 408 or code == 409 or code == 429;
}

pub const Client = struct {
    allocator: Allocator,
    base_url: []const u8,
    api_key: ?[]const u8,
    max_retries: u32,
    timeout_ms: u64,

    pub fn init(allocator: Allocator, options: ClientOptions) Client {
        return .{
            .allocator = allocator,
            .base_url = options.base_url orelse std.posix.getenv("VERS_BASE_URL") orelse "https://api.vers.sh",
            .api_key = options.api_key orelse std.posix.getenv("VERS_API_KEY"),
            .max_retries = options.max_retries,
            .timeout_ms = options.timeout_ms,
        };
    }

    fn doRequest(self: *const Client, method: std.http.Method, path: []const u8, body_json: ?[]const u8, opts: ?RequestOptions) (ApiError || Allocator.Error || error{HttpRequestFailed})!Response {
        _ = opts;
        var last_status: std.http.Status = .internal_server_error;

        for (0..self.max_retries + 1) |attempt| {
            if (attempt > 0) {
                const shift: std.math.Log2Int(u64) = @intCast(attempt - 1);
                const base_ms: u64 = 500 * std.math.shl(u64, 1, shift);
                std.Thread.sleep(base_ms * std.time.ns_per_ms);
            }

            const url_str = std.fmt.allocPrint(self.allocator, "{s}{s}", .{ self.base_url, path }) catch |e| return e;
            defer self.allocator.free(url_str);

            var http_client = std.http.Client{ .allocator = self.allocator };
            defer http_client.deinit();

            const auth = if (self.api_key) |key|
                std.fmt.allocPrint(self.allocator, "Bearer {s}", .{key}) catch |e| return e
            else
                null;
            defer if (auth) |a| self.allocator.free(a);

            var resp_body: std.ArrayList(u8) = .{};
            errdefer resp_body.deinit(self.allocator);

            var old_writer = resp_body.writer(self.allocator);
            var adapter_buf: [8192]u8 = undefined;
            var adapter = old_writer.adaptToNewApi(&adapter_buf);

            const extra_hdrs: []const std.http.Header = if (auth) |a|
                &.{ .{ .name = "authorization", .value = a }, .{ .name = "content-type", .value = "application/json" } }
            else
                &.{ .{ .name = "content-type", .value = "application/json" } };

            const result = http_client.fetch(.{
                .location = .{ .url = url_str },
                .method = method,
                .payload = body_json,
                .extra_headers = extra_hdrs,
                .response_writer = &adapter.new_interface,
            }) catch return ApiError.ConnectionError;

            adapter.new_interface.flush() catch {};

            last_status = result.status;
            if (isRetryable(result.status) and attempt < self.max_retries) continue;
            try statusToError(result.status);

            return Response{ .status = result.status, .body = resp_body.toOwnedSlice(self.allocator) catch |e| return e, .allocator = self.allocator };
        }
        try statusToError(last_status);
        return ApiError.ConnectionError;
    }

    /// 
    pub fn resize_vm_disk(self: *const Client, vm_id: []const u8, body: []const u8, skip_wait_boot: ?bool, opts: ?RequestOptions) !Response {
        const base_path = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/{s}/disk", .{ vm_id });
        defer self.allocator.free(base_path);
        var qbuf: std.ArrayList(u8) = .{};
        defer qbuf.deinit(self.allocator);
        try qbuf.appendSlice(self.allocator, base_path);
        var sep: u8 = '?';
        if (skip_wait_boot) |v| { try qbuf.append(self.allocator, sep); try qbuf.appendSlice(self.allocator, "skip_wait_boot="); const vs = try std.fmt.allocPrint(self.allocator, "{}", .{v}); defer self.allocator.free(vs); try qbuf.appendSlice(self.allocator, vs); sep = '&'; }
        const path = try qbuf.toOwnedSlice(self.allocator);
        defer self.allocator.free(path);
        return self.doRequest(.PATCH, path, body, opts);
    }

    /// 
    pub fn create_new_root_vm(self: *const Client, body: []const u8, wait_boot: ?bool, opts: ?RequestOptions) !Response {
        var qbuf: std.ArrayList(u8) = .{};
        defer qbuf.deinit(self.allocator);
        try qbuf.appendSlice(self.allocator, "/api/v1/vm/new_root");
        var sep: u8 = '?';
        if (wait_boot) |v| { try qbuf.append(self.allocator, sep); try qbuf.appendSlice(self.allocator, "wait_boot="); const vs = try std.fmt.allocPrint(self.allocator, "{}", .{v}); defer self.allocator.free(vs); try qbuf.appendSlice(self.allocator, vs); sep = '&'; }
        const path = try qbuf.toOwnedSlice(self.allocator);
        defer self.allocator.free(path);
        return self.doRequest(.POST, path, body, opts);
    }

    /// 
    pub fn branch_by_ref(self: *const Client, repo_name: []const u8, tag_name: []const u8, body: []const u8, count: ?u32, opts: ?RequestOptions) !Response {
        const base_path = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/branch/by_ref/{s}/{s}", .{ repo_name, tag_name });
        defer self.allocator.free(base_path);
        var qbuf: std.ArrayList(u8) = .{};
        defer qbuf.deinit(self.allocator);
        try qbuf.appendSlice(self.allocator, base_path);
        var sep: u8 = '?';
        if (count) |v| { try qbuf.append(self.allocator, sep); try qbuf.appendSlice(self.allocator, "count="); const vs = try std.fmt.allocPrint(self.allocator, "{}", .{v}); defer self.allocator.free(vs); try qbuf.appendSlice(self.allocator, vs); sep = '&'; }
        const path = try qbuf.toOwnedSlice(self.allocator);
        defer self.allocator.free(path);
        return self.doRequest(.POST, path, body, opts);
    }

    /// 
    pub fn list_public_commits(self: *const Client, opts: ?RequestOptions) !Response {
        return self.doRequest(.GET, "/api/v1/commits/public", null, opts);
    }

    /// 
    pub fn list_public_repo_tags(self: *const Client, org_name: []const u8, repo_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/public/repositories/{s}/{s}/tags", .{ org_name, repo_name });
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// 
    pub fn branch_by_tag(self: *const Client, tag_name: []const u8, body: []const u8, count: ?u32, opts: ?RequestOptions) !Response {
        const base_path = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/branch/by_tag/{s}", .{ tag_name });
        defer self.allocator.free(base_path);
        var qbuf: std.ArrayList(u8) = .{};
        defer qbuf.deinit(self.allocator);
        try qbuf.appendSlice(self.allocator, base_path);
        var sep: u8 = '?';
        if (count) |v| { try qbuf.append(self.allocator, sep); try qbuf.appendSlice(self.allocator, "count="); const vs = try std.fmt.allocPrint(self.allocator, "{}", .{v}); defer self.allocator.free(vs); try qbuf.appendSlice(self.allocator, vs); sep = '&'; }
        const path = try qbuf.toOwnedSlice(self.allocator);
        defer self.allocator.free(path);
        return self.doRequest(.POST, path, body, opts);
    }

    /// 
    pub fn branch_vm(self: *const Client, vm_or_commit_id: []const u8, body: []const u8, keep_paused: ?bool, skip_wait_boot: ?bool, count: ?u32, opts: ?RequestOptions) !Response {
        const base_path = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/{s}/branch", .{ vm_or_commit_id });
        defer self.allocator.free(base_path);
        var qbuf: std.ArrayList(u8) = .{};
        defer qbuf.deinit(self.allocator);
        try qbuf.appendSlice(self.allocator, base_path);
        var sep: u8 = '?';
        if (keep_paused) |v| { try qbuf.append(self.allocator, sep); try qbuf.appendSlice(self.allocator, "keep_paused="); const vs = try std.fmt.allocPrint(self.allocator, "{}", .{v}); defer self.allocator.free(vs); try qbuf.appendSlice(self.allocator, vs); sep = '&'; }
        if (skip_wait_boot) |v| { try qbuf.append(self.allocator, sep); try qbuf.appendSlice(self.allocator, "skip_wait_boot="); const vs = try std.fmt.allocPrint(self.allocator, "{}", .{v}); defer self.allocator.free(vs); try qbuf.appendSlice(self.allocator, vs); sep = '&'; }
        if (count) |v| { try qbuf.append(self.allocator, sep); try qbuf.appendSlice(self.allocator, "count="); const vs = try std.fmt.allocPrint(self.allocator, "{}", .{v}); defer self.allocator.free(vs); try qbuf.appendSlice(self.allocator, vs); sep = '&'; }
        const path = try qbuf.toOwnedSlice(self.allocator);
        defer self.allocator.free(path);
        return self.doRequest(.POST, path, body, opts);
    }

    /// 
    pub fn get_repo_tag(self: *const Client, repo_name: []const u8, tag_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/repositories/{s}/tags/{s}", .{ repo_name, tag_name });
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// 
    pub fn delete_repo_tag(self: *const Client, repo_name: []const u8, tag_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/repositories/{s}/tags/{s}", .{ repo_name, tag_name });
        defer self.allocator.free(path);
        return self.doRequest(.DELETE, path, null, opts);
    }

    /// 
    pub fn update_repo_tag(self: *const Client, repo_name: []const u8, tag_name: []const u8, body: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/repositories/{s}/tags/{s}", .{ repo_name, tag_name });
        defer self.allocator.free(path);
        return self.doRequest(.PATCH, path, body, opts);
    }

    /// 
    pub fn get_repository(self: *const Client, repo_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/repositories/{s}", .{ repo_name });
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// 
    pub fn delete_repository(self: *const Client, repo_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/repositories/{s}", .{ repo_name });
        defer self.allocator.free(path);
        return self.doRequest(.DELETE, path, null, opts);
    }

    /// 
    pub fn list_parent_commits(self: *const Client, commit_id: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/commits/{s}/parents", .{ commit_id });
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// 
    pub fn update_vm_state(self: *const Client, vm_id: []const u8, body: []const u8, skip_wait_boot: ?bool, opts: ?RequestOptions) !Response {
        const base_path = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/{s}/state", .{ vm_id });
        defer self.allocator.free(base_path);
        var qbuf: std.ArrayList(u8) = .{};
        defer qbuf.deinit(self.allocator);
        try qbuf.appendSlice(self.allocator, base_path);
        var sep: u8 = '?';
        if (skip_wait_boot) |v| { try qbuf.append(self.allocator, sep); try qbuf.appendSlice(self.allocator, "skip_wait_boot="); const vs = try std.fmt.allocPrint(self.allocator, "{}", .{v}); defer self.allocator.free(vs); try qbuf.appendSlice(self.allocator, vs); sep = '&'; }
        const path = try qbuf.toOwnedSlice(self.allocator);
        defer self.allocator.free(path);
        return self.doRequest(.PATCH, path, body, opts);
    }

    /// 
    pub fn fork_repository(self: *const Client, body: []const u8, opts: ?RequestOptions) !Response {
        return self.doRequest(.POST, "/api/v1/repositories/fork", body, opts);
    }

    /// 
    pub fn list_repositories(self: *const Client, opts: ?RequestOptions) !Response {
        return self.doRequest(.GET, "/api/v1/repositories", null, opts);
    }

    /// 
    pub fn create_repository(self: *const Client, body: []const u8, opts: ?RequestOptions) !Response {
        return self.doRequest(.POST, "/api/v1/repositories", body, opts);
    }

    /// 
    pub fn restore_from_commit(self: *const Client, body: []const u8, opts: ?RequestOptions) !Response {
        return self.doRequest(.POST, "/api/v1/vm/from_commit", body, opts);
    }

    /// 
    pub fn get_domain(self: *const Client, domain_id: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/domains/{s}", .{ domain_id });
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// 
    pub fn delete_domain(self: *const Client, domain_id: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/domains/{s}", .{ domain_id });
        defer self.allocator.free(path);
        return self.doRequest(.DELETE, path, null, opts);
    }

    /// 
    pub fn list_tags(self: *const Client, opts: ?RequestOptions) !Response {
        return self.doRequest(.GET, "/api/v1/commit_tags", null, opts);
    }

    /// 
    pub fn create_tag(self: *const Client, body: []const u8, opts: ?RequestOptions) !Response {
        return self.doRequest(.POST, "/api/v1/commit_tags", body, opts);
    }

    /// 
    pub fn list_public_repositories(self: *const Client, opts: ?RequestOptions) !Response {
        return self.doRequest(.GET, "/api/v1/public/repositories", null, opts);
    }

    /// 
    pub fn get_public_repo_tag(self: *const Client, org_name: []const u8, repo_name: []const u8, tag_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/public/repositories/{s}/{s}/tags/{s}", .{ org_name, repo_name, tag_name });
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// 
    pub fn get_vm_metadata(self: *const Client, vm_id: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/{s}/metadata", .{ vm_id });
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// 
    pub fn list_env_vars(self: *const Client, opts: ?RequestOptions) !Response {
        return self.doRequest(.GET, "/api/v1/env_vars", null, opts);
    }

    /// 
    pub fn set_env_vars(self: *const Client, body: []const u8, opts: ?RequestOptions) !Response {
        return self.doRequest(.PUT, "/api/v1/env_vars", body, opts);
    }

    /// 
    pub fn delete_vm(self: *const Client, vm_id: []const u8, skip_wait_boot: ?bool, opts: ?RequestOptions) !Response {
        const base_path = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/{s}", .{ vm_id });
        defer self.allocator.free(base_path);
        var qbuf: std.ArrayList(u8) = .{};
        defer qbuf.deinit(self.allocator);
        try qbuf.appendSlice(self.allocator, base_path);
        var sep: u8 = '?';
        if (skip_wait_boot) |v| { try qbuf.append(self.allocator, sep); try qbuf.appendSlice(self.allocator, "skip_wait_boot="); const vs = try std.fmt.allocPrint(self.allocator, "{}", .{v}); defer self.allocator.free(vs); try qbuf.appendSlice(self.allocator, vs); sep = '&'; }
        const path = try qbuf.toOwnedSlice(self.allocator);
        defer self.allocator.free(path);
        return self.doRequest(.DELETE, path, null, opts);
    }

    /// 
    pub fn list_commits(self: *const Client, opts: ?RequestOptions) !Response {
        return self.doRequest(.GET, "/api/v1/commits", null, opts);
    }

    /// 
    pub fn get_tag(self: *const Client, tag_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/commit_tags/{s}", .{ tag_name });
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// 
    pub fn delete_tag(self: *const Client, tag_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/commit_tags/{s}", .{ tag_name });
        defer self.allocator.free(path);
        return self.doRequest(.DELETE, path, null, opts);
    }

    /// 
    pub fn update_tag(self: *const Client, tag_name: []const u8, body: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/commit_tags/{s}", .{ tag_name });
        defer self.allocator.free(path);
        return self.doRequest(.PATCH, path, body, opts);
    }

    /// 
    pub fn branch_by_vm(self: *const Client, vm_id: []const u8, body: []const u8, keep_paused: ?bool, skip_wait_boot: ?bool, count: ?u32, opts: ?RequestOptions) !Response {
        const base_path = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/branch/by_vm/{s}", .{ vm_id });
        defer self.allocator.free(base_path);
        var qbuf: std.ArrayList(u8) = .{};
        defer qbuf.deinit(self.allocator);
        try qbuf.appendSlice(self.allocator, base_path);
        var sep: u8 = '?';
        if (keep_paused) |v| { try qbuf.append(self.allocator, sep); try qbuf.appendSlice(self.allocator, "keep_paused="); const vs = try std.fmt.allocPrint(self.allocator, "{}", .{v}); defer self.allocator.free(vs); try qbuf.appendSlice(self.allocator, vs); sep = '&'; }
        if (skip_wait_boot) |v| { try qbuf.append(self.allocator, sep); try qbuf.appendSlice(self.allocator, "skip_wait_boot="); const vs = try std.fmt.allocPrint(self.allocator, "{}", .{v}); defer self.allocator.free(vs); try qbuf.appendSlice(self.allocator, vs); sep = '&'; }
        if (count) |v| { try qbuf.append(self.allocator, sep); try qbuf.appendSlice(self.allocator, "count="); const vs = try std.fmt.allocPrint(self.allocator, "{}", .{v}); defer self.allocator.free(vs); try qbuf.appendSlice(self.allocator, vs); sep = '&'; }
        const path = try qbuf.toOwnedSlice(self.allocator);
        defer self.allocator.free(path);
        return self.doRequest(.POST, path, body, opts);
    }

    /// 
    pub fn delete_env_var(self: *const Client, key: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/env_vars/{s}", .{ key });
        defer self.allocator.free(path);
        return self.doRequest(.DELETE, path, null, opts);
    }

    /// 
    pub fn ssh_key(self: *const Client, vm_id: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/{s}/ssh_key", .{ vm_id });
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// 
    pub fn commit_vm(self: *const Client, vm_id: []const u8, body: []const u8, keep_paused: ?bool, skip_wait_boot: ?bool, opts: ?RequestOptions) !Response {
        const base_path = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/{s}/commit", .{ vm_id });
        defer self.allocator.free(base_path);
        var qbuf: std.ArrayList(u8) = .{};
        defer qbuf.deinit(self.allocator);
        try qbuf.appendSlice(self.allocator, base_path);
        var sep: u8 = '?';
        if (keep_paused) |v| { try qbuf.append(self.allocator, sep); try qbuf.appendSlice(self.allocator, "keep_paused="); const vs = try std.fmt.allocPrint(self.allocator, "{}", .{v}); defer self.allocator.free(vs); try qbuf.appendSlice(self.allocator, vs); sep = '&'; }
        if (skip_wait_boot) |v| { try qbuf.append(self.allocator, sep); try qbuf.appendSlice(self.allocator, "skip_wait_boot="); const vs = try std.fmt.allocPrint(self.allocator, "{}", .{v}); defer self.allocator.free(vs); try qbuf.appendSlice(self.allocator, vs); sep = '&'; }
        const path = try qbuf.toOwnedSlice(self.allocator);
        defer self.allocator.free(path);
        return self.doRequest(.POST, path, body, opts);
    }

    /// 
    pub fn delete_commit(self: *const Client, commit_id: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/commits/{s}", .{ commit_id });
        defer self.allocator.free(path);
        return self.doRequest(.DELETE, path, null, opts);
    }

    /// 
    pub fn update_commit(self: *const Client, commit_id: []const u8, body: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/commits/{s}", .{ commit_id });
        defer self.allocator.free(path);
        return self.doRequest(.PATCH, path, body, opts);
    }

    /// 
    pub fn list_repo_tags(self: *const Client, repo_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/repositories/{s}/tags", .{ repo_name });
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// 
    pub fn create_repo_tag(self: *const Client, repo_name: []const u8, body: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/repositories/{s}/tags", .{ repo_name });
        defer self.allocator.free(path);
        return self.doRequest(.POST, path, body, opts);
    }

    /// 
    pub fn list_vms(self: *const Client, opts: ?RequestOptions) !Response {
        return self.doRequest(.GET, "/api/v1/vms", null, opts);
    }

    /// 
    pub fn set_repository_visibility(self: *const Client, repo_name: []const u8, body: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/repositories/{s}/visibility", .{ repo_name });
        defer self.allocator.free(path);
        return self.doRequest(.PATCH, path, body, opts);
    }

    /// 
    pub fn list_domains(self: *const Client, vm_id: ?[]const u8, opts: ?RequestOptions) !Response {
        var qbuf: std.ArrayList(u8) = .{};
        defer qbuf.deinit(self.allocator);
        try qbuf.appendSlice(self.allocator, "/api/v1/domains");
        var sep: u8 = '?';
        if (vm_id) |v| { try qbuf.append(self.allocator, sep); try qbuf.appendSlice(self.allocator, "vm_id="); const vs = try std.fmt.allocPrint(self.allocator, "{}", .{v}); defer self.allocator.free(vs); try qbuf.appendSlice(self.allocator, vs); sep = '&'; }
        const path = try qbuf.toOwnedSlice(self.allocator);
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// 
    pub fn create_domain(self: *const Client, body: []const u8, opts: ?RequestOptions) !Response {
        return self.doRequest(.POST, "/api/v1/domains", body, opts);
    }

    /// 
    pub fn vm_status(self: *const Client, vm_id: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/{s}/status", .{ vm_id });
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// 
    pub fn get_public_repository(self: *const Client, org_name: []const u8, repo_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/public/repositories/{s}/{s}", .{ org_name, repo_name });
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// 
    pub fn branch_by_commit(self: *const Client, commit_id: []const u8, body: []const u8, count: ?u32, opts: ?RequestOptions) !Response {
        const base_path = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/branch/by_commit/{s}", .{ commit_id });
        defer self.allocator.free(base_path);
        var qbuf: std.ArrayList(u8) = .{};
        defer qbuf.deinit(self.allocator);
        try qbuf.appendSlice(self.allocator, base_path);
        var sep: u8 = '?';
        if (count) |v| { try qbuf.append(self.allocator, sep); try qbuf.appendSlice(self.allocator, "count="); const vs = try std.fmt.allocPrint(self.allocator, "{}", .{v}); defer self.allocator.free(vs); try qbuf.appendSlice(self.allocator, vs); sep = '&'; }
        const path = try qbuf.toOwnedSlice(self.allocator);
        defer self.allocator.free(path);
        return self.doRequest(.POST, path, body, opts);
    }

};

test "client initializes with defaults" {
    const client = Client.init(std.testing.allocator, .{});
    try std.testing.expectEqualStrings("https://api.vers.sh", client.base_url);
    try std.testing.expect(client.max_retries == 2);
}
