// Generated by Sterling SDK Generator
// Orchestrator Control Plane API v0.1.0
//
// Zig SDK for the Vers VM orchestration platform.
// Uses std.http.Client for HTTP and std.json for serialization.

const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

/// Options for constructing a VersSdkClient.
pub const ClientOptions = struct {
    base_url: ?[]const u8 = null,
    api_key: ?[]const u8 = null,
    max_retries: u32 = 2,
    timeout_ms: u64 = 30_000,
};

/// Represents the JSON body of an API response (owned, must be freed).
pub const Response = struct {
    status: std.http.Status,
    body: []const u8,
    allocator: Allocator,

    pub fn deinit(self: *Response) void {
        self.allocator.free(self.body);
    }

    /// Parse body as JSON value. Caller must deinit the returned Parsed.
    pub fn json(self: *const Response) !std.json.Parsed(std.json.Value) {
        return std.json.parseFromSlice(
            std.json.Value,
            self.allocator,
            self.body,
            .{ .allocate = .alloc_always },
        );
    }
};

/// Per-request option overrides.
pub const RequestOptions = struct {
    timeout_ms: ?u64 = null,
};

/// API error returned when the server sends a non-2xx response.
pub const ApiError = error{
    BadRequest,
    Unauthorized,
    Forbidden,
    NotFound,
    Conflict,
    UnprocessableEntity,
    RateLimited,
    InternalServerError,
    ConnectionError,
    Unexpected,
};

fn statusToError(status: std.http.Status) ApiError!void {
    return switch (@intFromEnum(status)) {
        200...299 => {},
        400 => ApiError.BadRequest,
        401 => ApiError.Unauthorized,
        403 => ApiError.Forbidden,
        404 => ApiError.NotFound,
        409 => ApiError.Conflict,
        422 => ApiError.UnprocessableEntity,
        429 => ApiError.RateLimited,
        500...599 => ApiError.InternalServerError,
        else => ApiError.Unexpected,
    };
}

fn isRetryable(status: std.http.Status) bool {
    const code = @intFromEnum(status);
    return code >= 500 or code == 408 or code == 409 or code == 429;
}

/// Client for the Vers Orchestrator Control Plane API.
pub const Client = struct {
    allocator: Allocator,
    base_url: []const u8,
    api_key: ?[]const u8,
    max_retries: u32,
    timeout_ms: u64,

    pub fn init(allocator: Allocator, options: ClientOptions) Client {
        const base = options.base_url orelse
            std.posix.getenv("VERS_BASE_URL") orelse
            "https://api.vers.sh";
        const key = options.api_key orelse
            std.posix.getenv("VERS_API_KEY");
        return .{
            .allocator = allocator,
            .base_url = base,
            .api_key = key,
            .max_retries = options.max_retries,
            .timeout_ms = options.timeout_ms,
        };
    }

    // ── Internal request helper ────────────────────────────────────

    fn doRequest(
        self: *const Client,
        method: std.http.Method,
        path: []const u8,
        body_json: ?[]const u8,
        opts: ?RequestOptions,
    ) (ApiError || Allocator.Error || error{HttpRequestFailed})!Response {
        const timeout = if (opts) |o| o.timeout_ms orelse self.timeout_ms else self.timeout_ms;
        _ = timeout; // TODO: use for connection timeout

        var last_status: std.http.Status = .internal_server_error;

        for (0..self.max_retries + 1) |attempt| {
            if (attempt > 0) {
                // Exponential backoff with jitter
                const base_ms: u64 = 500 * std.math.shl(u64, 1, @intCast(attempt - 1));
                const sleep_ns = base_ms * std.time.ns_per_ms;
                std.time.sleep(sleep_ns);
            }

            // Build URL
            const url_str = std.fmt.allocPrint(self.allocator, "{s}{s}", .{ self.base_url, path }) catch |e| return e;
            defer self.allocator.free(url_str);

            const uri = std.Uri.parse(url_str) catch return ApiError.ConnectionError;

            var http_client = std.http.Client{ .allocator = self.allocator };
            defer http_client.deinit();

            var header_buf: [8192]u8 = undefined;

            var req = http_client.open(method, uri, .{
                .server_header_buffer = &header_buf,
                .extra_headers = if (self.api_key) |key|
                    &.{.{ .name = "authorization", .value = std.fmt.allocPrint(self.allocator, "Bearer {s}", .{key}) catch return error.OutOfMemory }}
                else
                    &.{},
            }) catch return ApiError.ConnectionError;
            defer req.deinit();

            req.headers.content_type = .{ .override = "application/json" };

            if (body_json) |b| {
                req.transfer_encoding = .{ .content_length = b.len };
            }

            req.send() catch return ApiError.ConnectionError;

            if (body_json) |b| {
                req.writer().writeAll(b) catch return ApiError.ConnectionError;
            }

            req.finish() catch return ApiError.ConnectionError;
            req.wait() catch return ApiError.ConnectionError;

            last_status = req.status;

            if (isRetryable(req.status) and attempt < self.max_retries) {
                continue;
            }

            try statusToError(req.status);

            // Read response body
            var body_list = std.ArrayList(u8).init(self.allocator);
            errdefer body_list.deinit();

            var buf: [4096]u8 = undefined;
            while (true) {
                const n = req.reader().read(&buf) catch return ApiError.ConnectionError;
                if (n == 0) break;
                body_list.appendSlice(buf[0..n]) catch |e| return e;
            }

            return Response{
                .status = req.status,
                .body = body_list.toOwnedSlice() catch |e| return e,
                .allocator = self.allocator,
            };
        }

        // All retries exhausted
        try statusToError(last_status);
        return ApiError.ConnectionError;
    }

    /// Build a path with interpolated segments, appending query parameters.
    fn buildPath(
        self: *const Client,
        comptime template: []const u8,
        path_args: anytype,
        query: anytype,
    ) Allocator.Error![]const u8 {
        const base_path = std.fmt.allocPrint(self.allocator, template, path_args) catch |e| return e;

        // Build query string
        var parts = std.ArrayList(u8).init(self.allocator);
        defer parts.deinit();
        parts.appendSlice(base_path) catch |e| {
            self.allocator.free(base_path);
            return e;
        };
        self.allocator.free(base_path);

        var first = true;
        inline for (std.meta.fields(@TypeOf(query))) |field| {
            if (@field(query, field.name)) |val| {
                const sep: u8 = if (first) '?' else '&';
                first = false;
                const val_str = std.fmt.allocPrint(self.allocator, "{}", .{val}) catch |e| return e;
                defer self.allocator.free(val_str);
                parts.append(sep) catch |e| return e;
                parts.appendSlice(field.name) catch |e| return e;
                parts.append('=') catch |e| return e;
                parts.appendSlice(val_str) catch |e| return e;
            }
        }

        return parts.toOwnedSlice() catch |e| return e;
    }

    fn noQuery() struct {} {
        return .{};
    }

    // ── VM Operations ──────────────────────────────────────────────

    /// List all VMs.
    pub fn listVms(self: *const Client, opts: ?RequestOptions) !Response {
        return self.doRequest(.GET, "/api/v1/vms", null, opts);
    }

    /// Get VM status.
    pub fn vmStatus(self: *const Client, vm_id: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/{s}/status", .{vm_id});
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// Get VM metadata.
    pub fn getVmMetadata(self: *const Client, vm_id: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/{s}/metadata", .{vm_id});
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// Get VM SSH key.
    pub fn sshKey(self: *const Client, vm_id: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/{s}/ssh_key", .{vm_id});
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// Create a new root VM.
    pub fn createNewRootVm(self: *const Client, body: []const u8, wait_boot: ?bool, opts: ?RequestOptions) !Response {
        const path = try self.buildPath("/api/v1/vm/new_root", .{}, .{ .wait_boot = wait_boot });
        defer self.allocator.free(path);
        return self.doRequest(.POST, path, body, opts);
    }

    /// Update VM state.
    pub fn updateVmState(self: *const Client, vm_id: []const u8, body: []const u8, skip_wait_boot: ?bool, opts: ?RequestOptions) !Response {
        const base = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/{s}/state", .{vm_id});
        defer self.allocator.free(base);
        const path = try self.buildPath("{s}", .{base}, .{ .skip_wait_boot = skip_wait_boot });
        defer self.allocator.free(path);
        return self.doRequest(.PATCH, path, body, opts);
    }

    /// Resize VM disk.
    pub fn resizeVmDisk(self: *const Client, vm_id: []const u8, body: []const u8, skip_wait_boot: ?bool, opts: ?RequestOptions) !Response {
        const base = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/{s}/disk", .{vm_id});
        defer self.allocator.free(base);
        const path = try self.buildPath("{s}", .{base}, .{ .skip_wait_boot = skip_wait_boot });
        defer self.allocator.free(path);
        return self.doRequest(.PATCH, path, body, opts);
    }

    /// Delete a VM.
    pub fn deleteVm(self: *const Client, vm_id: []const u8, skip_wait_boot: ?bool, opts: ?RequestOptions) !Response {
        const base = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/{s}", .{vm_id});
        defer self.allocator.free(base);
        const path = try self.buildPath("{s}", .{base}, .{ .skip_wait_boot = skip_wait_boot });
        defer self.allocator.free(path);
        return self.doRequest(.DELETE, path, null, opts);
    }

    /// Commit a VM.
    pub fn commitVm(self: *const Client, vm_id: []const u8, body: []const u8, keep_paused: ?bool, skip_wait_boot: ?bool, opts: ?RequestOptions) !Response {
        const base = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/{s}/commit", .{vm_id});
        defer self.allocator.free(base);
        const path = try self.buildPath("{s}", .{base}, .{ .keep_paused = keep_paused, .skip_wait_boot = skip_wait_boot });
        defer self.allocator.free(path);
        return self.doRequest(.POST, path, body, opts);
    }

    /// Branch a VM or commit.
    pub fn branchVm(self: *const Client, vm_or_commit_id: []const u8, body: []const u8, keep_paused: ?bool, skip_wait_boot: ?bool, count: ?u32, opts: ?RequestOptions) !Response {
        const base = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/{s}/branch", .{vm_or_commit_id});
        defer self.allocator.free(base);
        const path = try self.buildPath("{s}", .{base}, .{ .keep_paused = keep_paused, .skip_wait_boot = skip_wait_boot, .count = count });
        defer self.allocator.free(path);
        return self.doRequest(.POST, path, body, opts);
    }

    /// Branch by commit ID.
    pub fn branchByCommit(self: *const Client, commit_id: []const u8, body: []const u8, count: ?u32, opts: ?RequestOptions) !Response {
        const base = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/branch/by_commit/{s}", .{commit_id});
        defer self.allocator.free(base);
        const path = try self.buildPath("{s}", .{base}, .{ .count = count });
        defer self.allocator.free(path);
        return self.doRequest(.POST, path, body, opts);
    }

    /// Branch by VM ID.
    pub fn branchByVm(self: *const Client, vm_id: []const u8, body: []const u8, keep_paused: ?bool, skip_wait_boot: ?bool, count: ?u32, opts: ?RequestOptions) !Response {
        const base = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/branch/by_vm/{s}", .{vm_id});
        defer self.allocator.free(base);
        const path = try self.buildPath("{s}", .{base}, .{ .keep_paused = keep_paused, .skip_wait_boot = skip_wait_boot, .count = count });
        defer self.allocator.free(path);
        return self.doRequest(.POST, path, body, opts);
    }

    /// Branch by tag name.
    pub fn branchByTag(self: *const Client, tag_name: []const u8, body: []const u8, count: ?u32, opts: ?RequestOptions) !Response {
        const base = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/branch/by_tag/{s}", .{tag_name});
        defer self.allocator.free(base);
        const path = try self.buildPath("{s}", .{base}, .{ .count = count });
        defer self.allocator.free(path);
        return self.doRequest(.POST, path, body, opts);
    }

    /// Branch by ref.
    pub fn branchByRef(self: *const Client, repo_name: []const u8, tag_name: []const u8, body: []const u8, count: ?u32, opts: ?RequestOptions) !Response {
        const base = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/branch/by_ref/{s}/{s}", .{ repo_name, tag_name });
        defer self.allocator.free(base);
        const path = try self.buildPath("{s}", .{base}, .{ .count = count });
        defer self.allocator.free(path);
        return self.doRequest(.POST, path, body, opts);
    }

    /// Restore from commit.
    pub fn restoreFromCommit(self: *const Client, body: []const u8, opts: ?RequestOptions) !Response {
        return self.doRequest(.POST, "/api/v1/vm/from_commit", body, opts);
    }

    // ── Commit Operations ──────────────────────────────────────────

    /// List all commits.
    pub fn listCommits(self: *const Client, opts: ?RequestOptions) !Response {
        return self.doRequest(.GET, "/api/v1/commits", null, opts);
    }

    /// List public commits.
    pub fn listPublicCommits(self: *const Client, opts: ?RequestOptions) !Response {
        return self.doRequest(.GET, "/api/v1/commits/public", null, opts);
    }

    /// List parent commits.
    pub fn listParentCommits(self: *const Client, commit_id: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/vm/commits/{s}/parents", .{commit_id});
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// Update a commit.
    pub fn updateCommit(self: *const Client, commit_id: []const u8, body: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/commits/{s}", .{commit_id});
        defer self.allocator.free(path);
        return self.doRequest(.PATCH, path, body, opts);
    }

    /// Delete a commit.
    pub fn deleteCommit(self: *const Client, commit_id: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/commits/{s}", .{commit_id});
        defer self.allocator.free(path);
        return self.doRequest(.DELETE, path, null, opts);
    }

    // ── Tag Operations ─────────────────────────────────────────────

    /// List all tags.
    pub fn listTags(self: *const Client, opts: ?RequestOptions) !Response {
        return self.doRequest(.GET, "/api/v1/commit_tags", null, opts);
    }

    /// Create a tag.
    pub fn createTag(self: *const Client, body: []const u8, opts: ?RequestOptions) !Response {
        return self.doRequest(.POST, "/api/v1/commit_tags", body, opts);
    }

    /// Get a tag by name.
    pub fn getTag(self: *const Client, tag_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/commit_tags/{s}", .{tag_name});
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// Update a tag.
    pub fn updateTag(self: *const Client, tag_name: []const u8, body: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/commit_tags/{s}", .{tag_name});
        defer self.allocator.free(path);
        return self.doRequest(.PATCH, path, body, opts);
    }

    /// Delete a tag.
    pub fn deleteTag(self: *const Client, tag_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/commit_tags/{s}", .{tag_name});
        defer self.allocator.free(path);
        return self.doRequest(.DELETE, path, null, opts);
    }

    // ── Repository Operations ──────────────────────────────────────

    /// List repositories.
    pub fn listRepositories(self: *const Client, opts: ?RequestOptions) !Response {
        return self.doRequest(.GET, "/api/v1/repositories", null, opts);
    }

    /// Create a repository.
    pub fn createRepository(self: *const Client, body: []const u8, opts: ?RequestOptions) !Response {
        return self.doRequest(.POST, "/api/v1/repositories", body, opts);
    }

    /// Get a repository.
    pub fn getRepository(self: *const Client, repo_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/repositories/{s}", .{repo_name});
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// Delete a repository.
    pub fn deleteRepository(self: *const Client, repo_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/repositories/{s}", .{repo_name});
        defer self.allocator.free(path);
        return self.doRequest(.DELETE, path, null, opts);
    }

    /// Fork a repository.
    pub fn forkRepository(self: *const Client, body: []const u8, opts: ?RequestOptions) !Response {
        return self.doRequest(.POST, "/api/v1/repositories/fork", body, opts);
    }

    /// Set repository visibility.
    pub fn setRepositoryVisibility(self: *const Client, repo_name: []const u8, body: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/repositories/{s}/visibility", .{repo_name});
        defer self.allocator.free(path);
        return self.doRequest(.PATCH, path, body, opts);
    }

    // ── Repository Tag Operations ──────────────────────────────────

    /// List tags for a repository.
    pub fn listRepoTags(self: *const Client, repo_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/repositories/{s}/tags", .{repo_name});
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// Create a tag for a repository.
    pub fn createRepoTag(self: *const Client, repo_name: []const u8, body: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/repositories/{s}/tags", .{repo_name});
        defer self.allocator.free(path);
        return self.doRequest(.POST, path, body, opts);
    }

    /// Get a repository tag.
    pub fn getRepoTag(self: *const Client, repo_name: []const u8, tag_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/repositories/{s}/tags/{s}", .{ repo_name, tag_name });
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// Update a repository tag.
    pub fn updateRepoTag(self: *const Client, repo_name: []const u8, tag_name: []const u8, body: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/repositories/{s}/tags/{s}", .{ repo_name, tag_name });
        defer self.allocator.free(path);
        return self.doRequest(.PATCH, path, body, opts);
    }

    /// Delete a repository tag.
    pub fn deleteRepoTag(self: *const Client, repo_name: []const u8, tag_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/repositories/{s}/tags/{s}", .{ repo_name, tag_name });
        defer self.allocator.free(path);
        return self.doRequest(.DELETE, path, null, opts);
    }

    // ── Domain Operations ──────────────────────────────────────────

    /// List domains.
    pub fn listDomains(self: *const Client, vm_id: ?[]const u8, opts: ?RequestOptions) !Response {
        if (vm_id) |vid| {
            const path = try std.fmt.allocPrint(self.allocator, "/api/v1/domains?vm_id={s}", .{vid});
            defer self.allocator.free(path);
            return self.doRequest(.GET, path, null, opts);
        }
        return self.doRequest(.GET, "/api/v1/domains", null, opts);
    }

    /// Create a domain.
    pub fn createDomain(self: *const Client, body: []const u8, opts: ?RequestOptions) !Response {
        return self.doRequest(.POST, "/api/v1/domains", body, opts);
    }

    /// Get a domain.
    pub fn getDomain(self: *const Client, domain_id: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/domains/{s}", .{domain_id});
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// Delete a domain.
    pub fn deleteDomain(self: *const Client, domain_id: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/domains/{s}", .{domain_id});
        defer self.allocator.free(path);
        return self.doRequest(.DELETE, path, null, opts);
    }

    // ── Environment Variable Operations ────────────────────────────

    /// List environment variables.
    pub fn listEnvVars(self: *const Client, opts: ?RequestOptions) !Response {
        return self.doRequest(.GET, "/api/v1/env_vars", null, opts);
    }

    /// Set environment variables.
    pub fn setEnvVars(self: *const Client, body: []const u8, opts: ?RequestOptions) !Response {
        return self.doRequest(.PUT, "/api/v1/env_vars", body, opts);
    }

    /// Delete an environment variable.
    pub fn deleteEnvVar(self: *const Client, key: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/env_vars/{s}", .{key});
        defer self.allocator.free(path);
        return self.doRequest(.DELETE, path, null, opts);
    }

    // ── Public Repository Operations ───────────────────────────────

    /// List public repositories.
    pub fn listPublicRepositories(self: *const Client, opts: ?RequestOptions) !Response {
        return self.doRequest(.GET, "/api/v1/public/repositories", null, opts);
    }

    /// Get a public repository.
    pub fn getPublicRepository(self: *const Client, org_name: []const u8, repo_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/public/repositories/{s}/{s}", .{ org_name, repo_name });
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// List public repository tags.
    pub fn listPublicRepoTags(self: *const Client, org_name: []const u8, repo_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/public/repositories/{s}/{s}/tags", .{ org_name, repo_name });
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }

    /// Get a public repository tag.
    pub fn getPublicRepoTag(self: *const Client, org_name: []const u8, repo_name: []const u8, tag_name: []const u8, opts: ?RequestOptions) !Response {
        const path = try std.fmt.allocPrint(self.allocator, "/api/v1/public/repositories/{s}/{s}/tags/{s}", .{ org_name, repo_name, tag_name });
        defer self.allocator.free(path);
        return self.doRequest(.GET, path, null, opts);
    }
};

test "client initializes with defaults" {
    const client = Client.init(std.testing.allocator, .{});
    try std.testing.expectEqualStrings("https://api.vers.sh", client.base_url);
    try std.testing.expect(client.max_retries == 2);
}
